server:
  port: 8080
spring:
  application:
    name: MultiTenant
    accesskey: ''
    secretkey: ''
  datasource:
    url: 'jdbc:postgresql://localhost:5432/primary_database?ApplicationName=MultiTenant'
    username: ''
    password: ''
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  kafka:
    consumer:
      bootstrap-servers: 
      group-id: 
    listener:
      topics: 
  main:
    allow-circular-references: true